import { Body, Controller, HttpCode, HttpStatus, Post } from "@nestjs/common";
import { ApiOperation, ApiResponse, ApiTags } from "@nestjs/swagger";

import { AiService } from "./ai.service";
import { GenerateTemplateDto } from "./dto/generate-template.dto";

@ApiTags("AI")
@Controller("ai")
export class AiController {
  constructor(private readonly aiService: AiService) {}

  @Post("generate-template")
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: "Generate a CV template using AI",
    description:
      "Takes a style prompt and CV data, returns a complete HTML template generated by AI.",
  })
  @ApiResponse({
    status: 200,
    description: "HTML template generated successfully",
    schema: {
      type: "object",
      properties: {
        html: { type: "string" },
      },
    },
  })
  async generateTemplate(
    @Body() dto: GenerateTemplateDto,
  ): Promise<{ html: string }> {
    const html = await this.aiService.generateTemplate(dto.prompt, dto.cvData);

    return { html };
  }
}
